const culinaryKidsData = [
  {
    id: 1,
    img: '',
    recipeTitleEn: 'Mini Pita Pizzas',
    recipeTitleHe: 'מיני פיצה',
    recipeTitleAr: 'ميني بيتزا',
    ingredientsEn:
     "Mini pita breads or English muffins",
  "Tomato sauce or pizza sauce",
  "Shredded mozzarella cheese",
  "Pepperoni slices or other toppings (vegetables, ham, pineapple, etc.)",
  "Olive oil",
  "Dried oregano or Italian seasoning",
    ingredientsHe: '  "פיתות מיני או מאפינס אנגלי",
  "רוטב עגבניות או רוטב פיצה",
  "גבינת מוצרלה מגוררת",
  "פרוסות פפרוני או תוספות אחרות (ירקות, חזיר, אננס וכו')",
  "שמן זית",
  "אורגנו מיובש או תבלין איטלקי"',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 2,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 3,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 4,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 5,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 6,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 7,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 8,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 9,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 10,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 11,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 12,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 13,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 14,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 15,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
  {
    id: 16,
    img: '',
    recipeTitleEn: '',
    recipeTitleHe: '',
    recipeTitleAr: '',
    ingredientsEn: '',
    ingredientsHe: '',
    ingredientsAr: '',
    preparationMethodEn: '',
    preparationMethodHe: '',
    preparationMethodAr: '',
  },
]
